web/Models/Event.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System;

namespace web.Models
{
    public class Event
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int EventID { get; set; }
        public string? Title { get; set; }
        public DateTime? Date { get; set; }
        public string? UserID { get; set; }
        public int? VenueID { get; set; }
        public int? PerformerID { get; set; }
        public DateTime? DateCreated { get; set; }
        public DateTime? DateEdited { get; set; }
        public ApplicationUser? User { get; set; }
        public ICollection<Rating>? Ratings { get; set; }
        public Venue? Venue { get; set; }
        public Performer? Performer { get; set; }
        public ICollection<Ticket>? Tickets  { get; set; }
    }
}

web/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using web.Data;
using web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace web.Controllers
{
    public class EventsController : Controller
    {
        private readonly EkarteContext _context;
        private readonly UserManager<ApplicationUser> _usermanager;

        public EventsController(EkarteContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _usermanager = userManager;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            var ekarteContext = _context.Events.Include(Event => Event.Performer).Include(Event => Event.Venue);
            return View(await ekarteContext.ToListAsync());
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .Include(Event => Event.Performer)
                .Include(Event => Event.Venue)
                .Include(Event => Event.Tickets)
                .FirstOrDefaultAsync(m => m.EventID == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Tickets/5
        /*public IActionResult Tickets(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }
            
            var @eventWithTickets = _context.Events
                .Include(e => e.Tickets)
                .FirstOrDefault(e => e.EventID == id);

            if (@eventWithTickets == null)
            {
                return NotFound();
            }

            return View(@eventWithTickets);
        }*/


        // GET: Events/Create
        [Authorize]

        public IActionResult Create()
        {
            ViewData["PerformerID"] = new SelectList(_context.Performers, "PerformerID", "Name");
            ViewData["VenueID"] = new SelectList(_context.Venues, "VenueID", "Name");
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]

        

        public async Task<IActionResult> Create([Bind("EventID,Title,Date,UserID,VenueID,PerformerID,DateCreated,DateEdited")] Event @event)
        {
            var currentUser=await _usermanager.GetUserAsync(User);
            if (ModelState.IsValid)
            {
                @event.User=currentUser;
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PerformerID"] = new SelectList(_context.Performers, "PerformerID", "Name", @event.PerformerID);
            ViewData["VenueID"] = new SelectList(_context.Venues, "VenueID", "Name", @event.VenueID);
            return View(@event);
        }

        // GET: Events/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            ViewData["PerformerID"] = new SelectList(_context.Performers, "PerformerID", "Name", @event.PerformerID);
            ViewData["VenueID"] = new SelectList(_context.Venues, "VenueID", "Name", @event.VenueID);
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]

        public async Task<IActionResult> Edit(int id, [Bind("EventID,Title,Date,UserID,VenueID,PerformerID,DateCreated,DateEdited")] Event @event)
        {
            if (id != @event.EventID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.EventID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PerformerID"] = new SelectList(_context.Performers, "PerformerID", "Name", @event.PerformerID);
            ViewData["VenueID"] = new SelectList(_context.Venues, "VenueID", "Name", @event.VenueID);
            return View(@event);
        }

        // GET: Events/Delete/5
        [Authorize(Roles = "Administrator")]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Events == null)
            {
                return NotFound();
            }

            var @event = await _context.Events
                .Include(Event => Event.Performer)
                .Include(Event => Event.Venue)
                .FirstOrDefaultAsync(m => m.EventID == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Events == null)
            {
                return Problem("Entity set 'EkarteContext.Events'  is null.");
            }
            var @event = await _context.Events.FindAsync(id);
            if (@event != null)
            {
                _context.Events.Remove(@event);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
          return _context.Events.Any(e => e.EventID == id);
        }
    }
}

web/Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using web.Data;
using web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace web.Controllers
{
    public class PurchaseController : Controller
    {
        private readonly EkarteContext _context;
        private readonly UserManager<ApplicationUser> _usermanager;

        public PurchaseController(EkarteContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _usermanager = userManager;
        }

        // GET: Purchase/BuyTicket
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BuyTicket(int eventId, int ticketId)
        {
            // Assuming you have the necessary logic to retrieve the user ID
            
            var currentUser=await _usermanager.GetUserAsync(User);


            // Create a new purchase record
            var newPurchase = new Purchase
            {
                TicketID = ticketId,
                UserID = currentUser.Id,
                // You may need to set other properties based on your application logic
            };

            _context.Purchases.Add(newPurchase);
            await _context.SaveChangesAsync();

            // Store success message in TempData
            TempData["SuccessMessage"] = "Ticket purchased successfully!";

            // Redirect to the event details page or any other desired page
            return RedirectToAction("Details", "Events", new { id = eventId });
        }

        // GET: Purchase
        public async Task<IActionResult> Index()
        {
            var ekarteContext = _context.Purchases.Include(p => p.Ticket).Include(p => p.User);
            return View(await ekarteContext.ToListAsync());
        }

        // GET: Purchase/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Purchases == null)
            {
                return NotFound();
            }

            var purchase = await _context.Purchases
                .Include(p => p.Ticket)
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.PurchaseID == id);
            if (purchase == null)
            {
                return NotFound();
            }

            return View(purchase);
        }

        // GET: Purchase/Create
        public IActionResult Create()
        {
            ViewData["TicketID"] = new SelectList(_context.Tickets, "TicketID", "TicketID");
            ViewData["UserID"] = new SelectList(_context.ApplicationUsers, "Id", "Id");
            return View();
        }

        // POST: Purchase/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PurchaseID,TicketID,UserID")] Purchase purchase)
        {
            if (ModelState.IsValid)
            {
                _context.Add(purchase);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TicketID"] = new SelectList(_context.Tickets, "TicketID", "TicketID", purchase.TicketID);
            ViewData["UserID"] = new SelectList(_context.ApplicationUsers, "Id", "Id", purchase.UserID);
            return View(purchase);
        }

        // GET: Purchase/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Purchases == null)
            {
                return NotFound();
            }

            var purchase = await _context.Purchases.FindAsync(id);
            if (purchase == null)
            {
                return NotFound();
            }
            ViewData["TicketID"] = new SelectList(_context.Tickets, "TicketID", "TicketID", purchase.TicketID);
            ViewData["UserID"] = new SelectList(_context.ApplicationUsers, "Id", "Id", purchase.UserID);
            return View(purchase);
        }

        // POST: Purchase/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PurchaseID,TicketID,UserID")] Purchase purchase)
        {
            if (id != purchase.PurchaseID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(purchase);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PurchaseExists(purchase.PurchaseID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TicketID"] = new SelectList(_context.Tickets, "TicketID", "TicketID", purchase.TicketID);
            ViewData["UserID"] = new SelectList(_context.ApplicationUsers, "Id", "Id", purchase.UserID);
            return View(purchase);
        }

        // GET: Purchase/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Purchases == null)
            {
                return NotFound();
            }

            var purchase = await _context.Purchases
                .Include(p => p.Ticket)
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.PurchaseID == id);
            if (purchase == null)
            {
                return NotFound();
            }

            return View(purchase);
        }

        // POST: Purchase/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Purchases == null)
            {
                return Problem("Entity set 'EkarteContext.Purchases'  is null.");
            }
            var purchase = await _context.Purchases.FindAsync(id);
            if (purchase != null)
            {
                _context.Purchases.Remove(purchase);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PurchaseExists(int id)
        {
          return _context.Purchases.Any(e => e.PurchaseID == id);
        }
    }
}

web/Views/Events/Create.cshtml
@model web.Models.Event

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Venue" class="control-label"></label>
                <select asp-for="VenueID" class ="form-control" asp-items="ViewBag.VenueID"></select>
            </div>
            <div class="form-group">
                <a asp-controller="Venue" asp-action="Create">Add a Venue</a>
            </div>
            <div class="form-group">
                <label asp-for="Performer" class="control-label"></label>
                <select asp-for="PerformerID" class ="form-control" asp-items="ViewBag.PerformerID"></select>
            </div>
            <div class="form-group">
                <a asp-controller="Performer" asp-action="Create">Add a Performer</a>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

web/Views/Events/Delete.cshtml
@model web.Models.Event

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateEdited)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateEdited)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Venue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Venue.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Performer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Performer.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EventID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

web/Views/Events/Details.cshtml
@model web.Models.Event

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}
<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateEdited)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateEdited)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Venue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Venue.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Performer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Performer.Name)
        </dd>
    </dl>
    <h4>Tickets</h4>
    @foreach (var ticket in Model.Tickets)
    {
        <div style="border: 1px solid #494949; margin-bottom: 15px; padding: 10px; width: 300px;">
            <p style="font-weight: bold;">@ticket.Description</p>
            <p>Price: @ticket.Price EUR</p>
            
            <!-- Add other ticket information as needed -->

            @if (User.Identity.IsAuthenticated)
            {
                <form asp-controller="Purchase" asp-action="BuyTicket" method="post">
                    <input type="hidden" name="eventId" value="@Model.EventID" />
                    <input type="hidden" name="ticketId" value="@ticket.TicketID" />
                    <button type="submit">Buy Ticket</button>
                </form>
            }
            else
            {
                <a id="login" asp-area="Identity" asp-page="/Account/Login">Please log in to purchase tickets.</a>
            }
        </div>
    }
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.EventID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

web/Views/Events/Edit.cshtml
@model web.Models.Event

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EventID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Venue" class="control-label"></label>
                <select asp-for="VenueID" class="form-control" asp-items="ViewBag.VenueID"></select>
                <span asp-validation-for="VenueID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Performer" class="control-label"></label>
                <select asp-for="PerformerID" class="form-control" asp-items="ViewBag.PerformerID"></select>
                <span asp-validation-for="PerformerID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

web/Views/Events/Index.cshtml
@model IEnumerable<web.Models.Event>

@{
    ViewData["Title"] = "ALL EVENTS";
}

<h1>Events</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Venue)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Performer)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Venue.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Performer.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.EventID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.EventID">Details and tickets</a> |
                <a asp-action="Delete" asp-route-id="@item.EventID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>